- name: Create new EC2 instance
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  vars:
    name: "node"
    ami_id: "ami-0557a15b87f6559cf"
    instance_type: "t2.micro"
    key_name: "lab4nodekey"
    security_group: "sg-039bc72e193dbbf77"
    region: "us-east-1"
    subnet_id: "subnet-034bef42dfbe1ab97"

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        count: 1
        assign_public_ip: yes
      register: ec2
